# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Kuma Theme
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: '' # the subpath of your site, e.g. /blog
url: '' # the base hostname & protocol for your site, e.g. http://example.com

app_name: Bear
logo: /assets/img/bear.svg

main:
  header: 'Write beautifully on iPhone, iPad, and Mac'
  subheader: 'Bear is a beautiful, flexible writing app for crafting notes and prose.'
  mac_app_store: ''
  apple_app_store: ''
  show_subscription: true
  subscription_message: Get updates on Bear progress. No spam, ever.
  show_app_store_badge: true
  show_mac_app_badge: true

overview:
  summary_1:
    header: Use it everywhere
    description: Bear works on iPhone, iPad, and Mac, so you can write wherever inspiration strikes. Use todos to stay on task across every device.

  summary_2:
    header: Keep control
    description: Link notes to each other to build a body of work. Use hashtags to organize for the way you think. All notes are stored in portable plain text.

  previews:
    desktop: /assets/img/preview.png
    watch: /assets/img/preview-3.png
    phone: /assets/img/preview-2.png
    tablet: /assets/img/preview-4.png

preview:
  header: Welcome to Bear
  link: https://www.youtube.com/embed/dQw4w9WgXcQ

feature_1:
  header: Write your way
  description: Bear is perfect for everything from quick notes to in-depth essays. A focus mode helps you concentrate, and advanced markup options are an online writer's best friend. Full in-line image support brings your writing to life.
  preview: /assets/img/writing.jpg

feature_2:
  header: A beautiful setting
  description: Packed with beautiful themes and typography, and more options on the way, Bear makes your writing look great before and after publishing.
  preview: /assets/img/settings.jpg

feature_3:
  header: Editing tools and exports
  description: Bear's simple tools take the effort out of writing, whether you need to hit specific word counts and reading times, or you need to convert your writing into PDF and Word docs. With Bear's custom markup shortcuts, you can add style and links with just a tap or keystroke.
  preview: /assets/img/editing.jpg

features_overview:
  header: Bear features at a glance

  feature_set_1:
    - Advanced Markup Editor that supports and highlights over 20 programming languages
    - Rich previews while writing so you see prose, not code
    - In-line support for images and photos
    - Use Cross-Note Links to build a body of work, quickly reference other notes, and more
    - Quickly add todos to individual notes to keep yourself on task
    - Multiple themes to offer a style for everyone
    - Multiple export options including HTML, PDF, DOCX, MD, JPG, and more

  feature_set_2:
    - Smart Data Recognition of elements like links, emails, addresses, colors, and more to come
    - Hashtags to quickly find and organize notes however you like
    - One-tap formatting on iPhone and iPad with a custom shortcut bar
    - Focus Mode hides notes and other options when it matters
    - All your notes are stored in plain text for the ultimate in portability
    - Effortless, secure, and private multi-device sync via iCloud
    - Regular updates to keep you and your writing current

pricing:
  header: Pricing model
  description: >
    Many of Bear’s features are free to use on Mac, iPad, and iPhone. <br />
    You can create notes, add tags and attachments, and export to a variety of formats. <br /> <br />
    Bear Pro offer advanced features, including sync between all your devices, over a dozen beautiful themes, and more powerful export options. All this, and future Pro features, can be unlocked with a single in-app subscription that covers all your devices. <br /> <br />
    The Bear Pro subscription has two options <br /> <br />
    $1.49 monthly, which offers a one week free trial <br />
    $14.99 annually, which has a one month free trial <br /> <br />
    Prices may vary based on your region due to local tax laws and conversion rates from U.S. dollars.

social_media:
  header: Bear on the Web
  subheader: A collection of the parts of the internet dedicated to Bear.
  links:
    - title: Bear on Twitter
      subtitle: Do you think that the gentle tweet of a Bear is odd? We don't!
      link: ''
      img: '/assets/svg/twitter.svg'

    - title: /r/bearapp on Reddit
      subtitle: Redditor? Join the official subreddit for Bear.
      link: ''
      img: '/assets/svg/reddit.svg'

    - title: Bear on Facebook
      subtitle: Even bears have their own pages!
      link: ''
      img: '/assets/svg/facebook.svg'

subscription:
  header: Subscribe to Bear Newsletter
  message: No spam, ever. Your email address will only ever be used for Bear and Shiny Frog News and you can easily unsubscribe with a single click at any time.

footer:
  show_resources: true
  show_links: true

  resources:
    title: Resources
    links:
      - title: How to import your notes from Evernote
        link: ''

      - title: Safari Chrome and Firefox browser extensions
        link: ''

      - title: X-callback-url Scheme documentation
        link: ''

  links:
    - title: Twitter
      link: ''

    - title: Support
      link: ''

    - title: Blog
      link: ''

    - title: Press Kit
      link: ''

faqs:
  - section: general
  - entries:
      - title: About the Sidebar in Bear
        link: /faqs/about-the-sidebar.html
      - title: Advanced search options in Bear
        link: /faqs/about-the-sidebar.html
      - title: Backup & Restore
        link: /faqs/about-the-sidebar.html
      - title: Bear for Apple Watch overview
        link: Disable spell check and corrections
      - title: Drag & Drop on iPad and iPhone
        link: /faqs/about-the-sidebar.html
      - title: Hide notes with the Archive
        link: /faqs/about-the-sidebar.html
      - title: Hide the Sidebar and Note List on Mac and iPad
        link: /faqs/about-the-sidebar.html
      - title: How to blog with Bear on iPad and iPhone
        link: /faqs/about-the-sidebar.html
      - title: How to encrypt and lock notes with Bear
        link: /faqs/about-the-sidebar.html
      - title: How to fold tasks, show thumbnails in Bear
        link: /faqs/about-the-sidebar.html
      - title: How to lock Bear for privacy
        link: /faqs/about-the-sidebar.html
      - title: How to use Bear with Siri on iOS
        link: /faqs/about-the-sidebar.html
      - title: Open Bear notes in separate windows
        link: /faqs/about-the-sidebar.html
      - title: Print notes
        link: /faqs/about-the-sidebar.html
      - title: Quickly add emoji to notes
        link: /faqs/about-the-sidebar.html
      - title: Quickly navigate notes on iOS
        link: /faqs/about-the-sidebar.html
      - title: Typography options
        link: /faqs/about-the-sidebar.html
      - title: What about Bear for web, Android, or Windows
        link: /faqs/about-the-sidebar.html
      - title: Where are Bear's notes located
        link: /faqs/about-the-sidebar.html
      - title: X callback url Scheme documentation
        link: /faqs/about-the-sidebar.html
      - title: iMessage stickers
        link: /faqs/about-the-sidebar.html

blog_posts:
  - title: Bear turns 3
    created_at: November 27, 2019
    img: '/assets/img/bear.png'
    summary: Bear had quite the year! We presented at a conference, grew the team, released big new projects, and made great progress on others.
    link: /blog-posts/bear-turns-3.html

  - title: Bear turns 3
    created_at: November 27, 2019
    img: '/assets/img/bear.png'
    summary: Bear had quite the year! We presented at a conference, grew the team, released big new projects, and made great progress on others.
    link: /blog-posts/bear-turns-3.html

  - title: Bear turns 3
    created_at: November 27, 2019
    img: '/assets/img/bear.png'
    summary: Bear had quite the year! We presented at a conference, grew the team, released big new projects, and made great progress on others.
    link: /blog-posts/bear-turns-3.html

  - title: Bear turns 3
    created_at: November 27, 2019
    img: '/assets/img/bear.png'
    summary: Bear had quite the year! We presented at a conference, grew the team, released big new projects, and made great progress on others.
    link: /blog-posts/bear-turns-3.html

# Build settings
plugins:
  - jekyll-postcss
  - jekyll-purgecss
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
